name: Upload Website to S3 and Invalidate CloudFront
 
on:
  push:
    branches:
      - main  # Runs when code pushed to main branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
 
      # 2. Upload to S3
      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete 
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1  # Mumbai Region
          SOURCE_DIR: './'  # Change this to your actual folder containing index.html
 
      # 3. Invalidate CloudFront caches
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3G6480IK0RPB2  --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
